// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPHcGwdXQ2HLx8YGfH1xp_kWVAdaxviU',
    appId: '1:284479174704:web:1444b621d504cbd09b15f5',
    messagingSenderId: '284479174704',
    projectId: 'event-app-3024d',
    authDomain: 'event-app-3024d.firebaseapp.com',
    storageBucket: 'event-app-3024d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNjW_UrpxKLoTaIAZ26jqHebXX_EQVmNo',
    appId: '1:284479174704:android:97d1e11bf0d356949b15f5',
    messagingSenderId: '284479174704',
    projectId: 'event-app-3024d',
    storageBucket: 'event-app-3024d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMeMZzfVVLXS7nBOREOErt0o2udmxej0',
    appId: '1:284479174704:ios:7fa6eeae2dfb8f469b15f5',
    messagingSenderId: '284479174704',
    projectId: 'event-app-3024d',
    storageBucket: 'event-app-3024d.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMeMZzfVVLXS7nBOREOErt0o2udmxej0',
    appId: '1:284479174704:ios:7fa6eeae2dfb8f469b15f5',
    messagingSenderId: '284479174704',
    projectId: 'event-app-3024d',
    storageBucket: 'event-app-3024d.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmPHcGwdXQ2HLx8YGfH1xp_kWVAdaxviU',
    appId: '1:284479174704:web:6aa2449f2a8351c59b15f5',
    messagingSenderId: '284479174704',
    projectId: 'event-app-3024d',
    authDomain: 'event-app-3024d.firebaseapp.com',
    storageBucket: 'event-app-3024d.firebasestorage.app',
  );
}
